FROM alpine

RUN addgroup -S -g 1000 iperfgroup && \
    adduser -S -D -H -u 1000 iperfuser -G iperfgroup && \
    apk add --no-cache -X https://dl-cdn.alpinelinux.org/alpine/edge/main iperf3

USER iperfuser

EXPOSE 5201 5201/udp

ENTRYPOINT ["iperf3"]
